FROM curlimages/curl
USER root

# Install ArgoCD binary
RUN curl -sSL -o /usr/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64 && \
    chmod +x /usr/bin/argocd
