name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Docker login
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} || docker login -u photopills --password-stdin

    - name: Build Docker image
      run: docker build -f Dockerfile -t photopills/runner:latest .

    - name: Push Docker image
      run: docker push photopills/runner:latest
