name: Docker Image CI

on:
  push:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
        username: photopills
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build & Push Alpine Runner
      run: |
        docker build -f Dockerfile -t photopills/runner:alpine .
        docker tag photopills/runner:alpine photopills/runner:latest
        docker push photopills/runner:alpine
        docker push photopills/runner:latest
        
        # Debug image
        docker build -f Dockerfile.debug -t photopills/runner:debug .
        docker push photopills/runner:debug

    - name: Build & Push Python Runner
      run: |
        docker build -f Dockerfile.python -t photopills/runner:python .
        docker push photopills/runner:python
